name: Update game client

on:
  push:
    paths:
      - "update-action-version.txt"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_GITHUB_TOKEN }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - name: copy random file
      #   run: cp test.png test${{ github.run_number }}.png
      - name: copy random file
        run: echo "hello${{ github.run_number }}" > test24.png

      - uses: invisionapp/private-action-loader@v3
        id: output_example
        name: Update game client & push
        with:
          pal-repo-token: ${{ secrets.REPOSITORY_GITHUB_TOKEN }}
          # IN PROD MUST BE refs/remotes/origin/master
          pal-repo-name: ciberusps/game-clients-tracking@refs/remotes/origin/development
          pal-action-directory: ./.github/actions/update/
          repository: ${{ github.repository }}
          steam-game-id: ${{ secrets.STEAM_GAME_ID }}
          steam-account-nickname: ${{ secrets.STEAM_ACCOUNT_NICKNAME }}
          steam-account-password: ${{ secrets.STEAM_ACCOUNT_PASSWORD }}
          bunny-cdn-api-key: ${{ secrets.BUNNY_CDN_API_KEY }}
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
